# Generated by Django 6.0.3 on 2026-05-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('accounts', '0002_create_admin'),
    ]

    operations = [
    ]
