# Generated by Django 6.0.3 on 2026-05-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0002_remove_patient_date_of_birth_remove_patient_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.AddField(
            model_name='patient',
            name='admitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_inpatient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
