# Generated by Django 6.0.3 on 2026-05-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_doctor_remove_patient_assigned_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='priority',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
